version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
      - /data/node_modules
      
  web:
    image: nginx:1.20-alpine
    ports:
      - 8081:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data